version: '3.7'

services:
  kh-nasir:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: kh-nasir
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    env_file:
      - .env