# Generated by Django 4.2.2 on 2023-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circular_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locatin', models.CharField(default='بخشنامه ها', max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'تصاویر',
                'verbose_name_plural': 'تصاویر بخشنامه ها',
                'db_table': 'Circular_Images',
            },
        ),
        migrations.CreateModel(
            name='Works_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locatin', models.CharField(default='نمونه کار ها', max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'تصاویر',
                'verbose_name_plural': 'تصاویر نمونه کار ها',
                'db_table': 'Works_Images',
            },
        ),
    ]
