# Generated by Django 4.2.2 on 2023-09-10 11:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='اطلاعات هنرستان')),
                ('location', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='موقیعت مکانی هنرستان')),
                ('phone', models.CharField(max_length=200, verbose_name='شماره تلفن هنرستان')),
                ('slogan', models.CharField(default=None, max_length=200, verbose_name='شعار هنرستان')),
            ],
            options={
                'verbose_name': 'اطلاعات هنرستان',
                'verbose_name_plural': 'اطلاعات هنرستان',
            },
        ),
        migrations.CreateModel(
            name='HomePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='تصویر اسلایدر')),
            ],
            options={
                'verbose_name': 'تصویر هنرستان',
                'verbose_name_plural': 'تصاویر هنرستان',
            },
        ),
    ]
