# Generated by Django 4.2.2 on 2023-09-10 11:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ادرس ای پی ')),
            ],
            options={
                'verbose_name': 'آی پی',
                'verbose_name_plural': 'آی پی ها',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان اطلاعیه')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن اطلاعیه')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده')], default='d', max_length=1, verbose_name='وضعیت')),
                ('hits', models.ManyToManyField(blank=True, related_name='hits', to='notifications.ipaddress', verbose_name='بازدید ها')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه ها',
                'db_table': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان بخشنامه')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن بخشنامه')),
                ('image', models.ImageField(upload_to='images/', verbose_name='تصویر بخشنامه')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار بخشنامه')),
                ('status', models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده')], default='d', max_length=1, verbose_name='وضعیت')),
                ('visits', models.ManyToManyField(blank=True, related_name='visits', to='notifications.ipaddress', verbose_name='بازدید ها')),
            ],
            options={
                'verbose_name': 'بخشنامه',
                'verbose_name_plural': 'بخشنامه ها',
                'db_table': 'Circular',
            },
        ),
    ]
